language: python
python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install -e .
# command to run tests
script: 
  - pytest --cov=./
  - xvfb-run --server-args="-screen 0 1280x1024x16" make test

after_success:
  - codecov