language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install -e .
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - pytest --cov=./

after_success:
  - codecov