language: python
python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install pytest pytest-cov
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: 
  - pytest
  - pytest --cov=./

after_success:
  - codecov